# Generated by Django 3.2.7 on 2021-09-17 11:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('category_name', models.CharField(default='', max_length=50, verbose_name='Category-Name')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Enterprise_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('enterprise_name', models.CharField(max_length=50, verbose_name='Enterprise-Name')),
                ('enterprise_password', models.CharField(max_length=50, verbose_name='Password')),
                ('enterprise_email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('enterprise_photo', models.ImageField(upload_to='Enterprise/profile_photo', verbose_name='Profile-photo')),
                ('enterprise_contact', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('product_name', models.CharField(max_length=50, verbose_name='Product-Name')),
                ('product_img', models.ImageField(upload_to='Product', verbose_name='Product-image')),
                ('Price', models.PositiveIntegerField(verbose_name='price')),
                ('Description', models.TextField(verbose_name='Description')),
                ('product_qty', models.PositiveIntegerField(verbose_name='Product-quantity')),
                ('product_categories', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Enterprise.categories', verbose_name='Product-Categories')),
                ('product_enterprsie', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Enterprise.enterprise_detail', verbose_name='Product-Enterprise')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
