# Generated by Django 3.2.7 on 2021-09-14 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_name', models.CharField(max_length=50, verbose_name='Name')),
                ('enterprise_password', models.CharField(max_length=50, verbose_name='Password')),
                ('enterprise_email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('enterprise_photo', models.ImageField(upload_to='enterprise_upload/profile_photo', verbose_name='Photo')),
                ('enterprise_contact', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
            ],
        ),
    ]
