# Generated by Django 3.2.7 on 2021-09-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enterprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50, verbose_name='Category-Name')),
            ],
        ),
        migrations.AlterField(
            model_name='enterprise_detail',
            name='enterprise_name',
            field=models.CharField(max_length=50, verbose_name='Enterprise-Name'),
        ),
    ]
