# Generated by Django 3.2.7 on 2021-09-20 10:26

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Enterprise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise_detail',
            name='enterprise_categories',
            field=djongo.models.fields.ArrayReferenceField(default='', on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='Enterprise.categories', verbose_name='Enterprise-Categories'),
        ),
    ]
