# Generated by Django 3.2.7 on 2021-09-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enterprise', '0002_auto_20210914_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='cat_name',
            new_name='category_name',
        ),
        migrations.AddField(
            model_name='enterprise_detail',
            name='enterprise_categories',
            field=models.ManyToManyField(to='Enterprise.Categories', verbose_name='Categories'),
        ),
    ]
