# Generated by Django 3.2.7 on 2021-09-14 11:01

from django.db import migrations
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Enterprise', '0003_auto_20210914_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='enterprise_detail',
            name='enterprise_categories',
        ),
        migrations.AddField(
            model_name='enterprise_detail',
            name='enterprise_categories',
            field=djongo.models.fields.ArrayReferenceField(default='', on_delete=django.db.models.deletion.CASCADE, to='Enterprise.categories'),
        ),
    ]
