# Generated by Django 3.2.7 on 2021-09-15 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enterprise', '0004_auto_20210914_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise_detail',
            name='enterprise_photo',
            field=models.ImageField(upload_to='Enterprise/profile_photo', verbose_name='Profile-photo'),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Product-Name')),
                ('product_img', models.ImageField(upload_to='Product', verbose_name='Product-image')),
                ('Price', models.PositiveIntegerField(verbose_name='price')),
                ('Description', models.TextField(verbose_name='Description')),
                ('product_qty', models.PositiveIntegerField(verbose_name='Product-quantity')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enterprise.categories', verbose_name='Product-Category')),
                ('product_enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enterprise.enterprise_detail', verbose_name='Product-Enterprise')),
            ],
        ),
    ]
