# Generated by Django 3.2.7 on 2021-09-16 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enterprise', '0005_auto_20210915_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
