# Generated by Django 3.2.7 on 2021-09-16 12:42

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Enterprise', '0007_alter_products_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_category',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='product_enterprise', on_delete=django.db.models.deletion.CASCADE, to='Enterprise.categories'),
        ),
    ]
