# Generated by Django 3.2.7 on 2021-09-17 04:32

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Enterprise', '0009_auto_20210916_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='enterprise_list',
        ),
        migrations.AddField(
            model_name='enterprise_detail',
            name='enterprise_categories',
            field=djongo.models.fields.ArrayReferenceField(default='', on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='Enterprise.categories', verbose_name='Enterprise-categories'),
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_category',
        ),
        migrations.AddField(
            model_name='products',
            name='product_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Enterprise.categories', verbose_name='Product-cat'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_enterprise',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='product_category', chained_model_field='enterprise_categories', on_delete=django.db.models.deletion.CASCADE, to='Enterprise.enterprise_detail', verbose_name='Product-cat'),
        ),
    ]
