# Generated by Django 3.2.7 on 2021-09-17 05:17

from django.db import migrations, models
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Enterprise', '0010_auto_20210917_0432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_category',
            new_name='product_categories',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_enterprise',
        ),
        migrations.AddField(
            model_name='products',
            name='product_enterprsie',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='product_categories', chained_model_field='enterprise_categories', to='Enterprise.Enterprise_Detail', verbose_name='Product-ent'),
        ),
        migrations.RemoveField(
            model_name='enterprise_detail',
            name='enterprise_categories',
        ),
        migrations.AddField(
            model_name='enterprise_detail',
            name='enterprise_categories',
            field=models.ManyToManyField(to='Enterprise.Categories', verbose_name='Enterprise-Categories'),
        ),
    ]
