# Generated by Django 3.2.7 on 2021-09-17 05:24

from django.db import migrations
import djongo.models.fields
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Enterprise', '0011_auto_20210917_0517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise_detail',
            name='enterprise_categories',
        ),
        migrations.AddField(
            model_name='enterprise_detail',
            name='enterprise_categories',
            field=djongo.models.fields.ArrayReferenceField(default='', on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='Enterprise.categories', verbose_name='Enterprise-Categories'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_enterprsie',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='product_categories', chained_model_field='enterprise_categories', horizontal=True, to='Enterprise.Enterprise_Detail', verbose_name='Product-ent'),
        ),
    ]
