# Generated by Django 3.2.7 on 2021-09-17 05:38

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Enterprise', '0012_auto_20210917_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_enterprsie',
        ),
        migrations.AddField(
            model_name='products',
            name='product_enterprsie',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='product_categories', chained_model_field='enterprise_categories', default='', on_delete=django.db.models.deletion.CASCADE, to='Enterprise.enterprise_detail', verbose_name='Product-ent'),
        ),
    ]
