# Generated by Django 3.2.7 on 2021-09-13 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='UserName')),
                ('user_password', models.CharField(max_length=50, verbose_name='Password')),
                ('user_email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('user_photo', models.ImageField(upload_to=None, verbose_name='Photo')),
                ('user_age', models.PositiveIntegerField(verbose_name='Age')),
                ('user_gender', models.CharField(max_length=50, verbose_name='Gender')),
                ('user_contact', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('user_address', models.TextField(verbose_name='Address')),
            ],
        ),
    ]
