# Generated by Django 3.2.7 on 2021-10-01 12:21

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50, verbose_name='UserName')),
                ('user_password', models.CharField(max_length=50, verbose_name='Password')),
                ('user_email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('user_photo', models.ImageField(upload_to='User/profile_photo', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Profile-photo')),
                ('user_age', models.PositiveIntegerField(verbose_name='Age')),
                ('user_gender', models.CharField(max_length=50, verbose_name='Gender')),
                ('user_contact', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{10}$')])),
                ('user_address', models.TextField(verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
    ]
