# Generated by Django 3.2.7 on 2021-10-08 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enterprise', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='qty',
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enterprise.products', verbose_name='product'),
        ),
    ]
