# Generated by Django 3.2.7 on 2021-10-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_address',
            new_name='user_address1',
        ),
        migrations.AddField(
            model_name='user',
            name='user_address2',
            field=models.TextField(blank=True, verbose_name='Address2'),
        ),
    ]
