# Generated by Django 3.2.7 on 2021-09-13 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_detail_user_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='user_contact',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
