# Generated by Django 3.2.7 on 2021-10-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20211008_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qty',
            field=models.PositiveIntegerField(default=1, verbose_name='Product-qty'),
        ),
    ]
