# Generated by Django 3.2.7 on 2021-10-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_order_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_date',
            field=models.DateField(auto_now=True, verbose_name='Ordered-Date'),
        ),
    ]
