# Generated by Django 3.2.7 on 2021-09-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_user_detail_user_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='user_photo',
            field=models.ImageField(upload_to='user_upload/profile_photo', verbose_name='Photo'),
        ),
    ]
