# Generated by Django 3.2.7 on 2021-09-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_user_detail_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='user_photo',
            field=models.ImageField(upload_to='User/profile_photo', verbose_name='Profile-photo'),
        ),
    ]
