# Generated by Django 3.2.7 on 2021-10-04 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enterprise', '0001_initial'),
        ('User', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.PositiveIntegerField(default='1', verbose_name='product_qty'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product_items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enterprise.products', verbose_name='Product-item'),
        ),
    ]
