# Generated by Django 3.2.7 on 2021-10-04 10:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Enterprise', '0001_initial'),
        ('User', '0006_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.PositiveIntegerField(default='1', verbose_name='product_qty')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('product_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enterprise.products', verbose_name='Product-item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.users', verbose_name='user')),
            ],
            options={
                'verbose_name_plural': 'Cart',
            },
        ),
    ]
