# Generated by Django 3.2.7 on 2021-10-04 12:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Enterprise', '0001_initial'),
        ('User', '0007_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.PositiveIntegerField(verbose_name='qty')),
                ('total', models.PositiveIntegerField(verbose_name='Total-Amount')),
                ('Address', models.TextField(verbose_name='Address')),
                ('status', models.CharField(choices=[('0', 'pending'), ('1', 'approved'), ('2', 'dispatched'), ('3', 'delievered'), ('4', 'cancelled')], max_length=50, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enterprise.products', verbose_name='product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.users', verbose_name='user')),
            ],
        ),
    ]
