# Generated by Django 3.2.7 on 2021-10-06 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Address',
            new_name='address',
        ),
    ]
